name: generate greetings

on:
  push:
    branches: [main]

jobs:
  my_job:
    name: Generate Greetings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create greetings file
        run: |
          echo "import sys" >> greetings.py
          echo "print('Hello, ${{ github.actor }}!')" >> greetings.py
          echo "print('Thank you for pushing to the repository.')" >> greetings.py
      
      - name: Show greetings
        run: python greetings.py
    
