name: x2qpcheese
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Create greetings file
        run: |
          echo "import sys" >> greetings.py
          echo "print('Hello, ${{ github.actor }}!')" >> greetings.py
          echo "print('Thank you for pushing to the repository.')" >> greetings.py
      
      - name: Show greetings file content
        run: cat greetings.py
